version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - xpulse
    volumes:
      - mongodb_data:/data/db

  xmock:
    build:
      context: ./xmock
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./xmock:/usr/src/app
    command: node server.js
    environment:
      - NODE_VERSION=20
    networks:
      - xpulse

volumes:
  mongodb_data:
  mongodb_config:

networks:
  xpulse:
    driver: bridge
